[package]
name = "bayesian_arima_for_time_series_analysis_in_python_rs"
description = "Python bindings (PyO3) for bayesian_arima_for_time_series_analysis_in_python_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "bayesian_arima_for_time_series_analysis_in_python_rs"
crate-type = ["cdylib"]

[dependencies]
bayesian_arima_for_time_series_analysis_in_python_core = { path = "../core" }
pyo3 = { version = "0.28", features = ["extension-module"] }
numpy = "0.28"
